### PR TITLE
Updated endpoint to match what is currently available

### PR DESCRIPTION
**Pull request by ghost**
See http://api.met.no/weatherapi/documentation

Be aware that it breaks the interface as for example the WindForecast does not appear to exist anymore.

### CODE REVIEW

**Comment by evanshortiss** [comment]
Hey @ktrance, thanks for the PR. I will review soon. It seems like some things are removed? Did you remove these since they are no longer part of the met.no API? This might require a MAJOR version bump?

**Comment by ktrance** [comment]
Hi @evanshortiss, 

I tried the windforecast API and got a 404. 

Checking the URL came back to with a "An error occurred!
The following error messages were generated:
[Tue Oct 25 04:44:23 2016] [error] [windforecast]

    The specified product does not exist

Specified parameters:

version=0.X
action=documentation
product=windforecast

See also...

    Top-level WeatherAPI documentation

If you believe this to be a bug in the application, contact the developers. Thanks! "

When going to the Top-level WeatherAPI documentation(http://api.met.no/weatherapi/documentation) it does appear that several API calls have been retired from the available products and a few added. I have updated the endpoints.js to reflect the current product list from the site.

About the version number then I considered bumping it a major version but figured I would let it be up to you so just put in the statement about the breaking API.

Let me know if you need me to bump it to 0.2.0.

**Comment by evanshortiss** [comment]
@ktrance could you rebase this to latest `master` branch? I will merge then. Apologies for delays 👍

**Comment by ktrance** [comment]
@evanshortiss done.

**Comment by evanshortiss** [comment]
@ktrance thanks I will ship in 2.0.0

**Comment by geira** [comment]
Plenty of more products which have been removed or updated to newer versions. Suggest you check the [Available JSON list](https://api.met.no/weatherapi/available.json) to see which products are currently in use.

**Comment by ghost** [comment]
> Plenty of more products which have been removed or updated to newer versions. Suggest you check the [Available JSON list](https://api.met.no/weatherapi/available.json) to see which products are currently in use.

This PR is 4 years old and was merged to master in 2017. You should probably create an issue or a PR if you want the package updated.

**Comment by geira** [comment]
Didn't want to have to repeat the context all over again. Anyway, this is just a heads-up that most of the functionality is going to break within the year and the library become unusable. Locationforecast/1.9 has been deprecated and will be removed soon. Suggest you plan ahead and contact us at weatherapi-adm@met.no if you have any questions.

**Pull request merged**
